CREATE TABLE CUSTOMER ( ID BIGINT NOT NULL, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), ADDRESS VARCHAR(1000), LICENSENUMBER VARCHAR(255), PRIMARY KEY (ID))
INSERT INTO CUSTOMER(ID, FIRSTNAME, LASTNAME, ADDRESS, LICENSENUMBER) values (1000, 'Murali', 'Anantha', '100 San Francisco Rd', '6CZZ465')
INSERT INTO CUSTOMER(ID, FIRSTNAME, LASTNAME, ADDRESS, LICENSENUMBER) values (1001, 'Ram', 'Kuchimanchi', '101 New York Rd', 'E4Y7897')
INSERT INTO CUSTOMER(ID, FIRSTNAME, LASTNAME, ADDRESS, LICENSENUMBER) values (1002, 'Sajjad', 'Raza', '102 Fremont Rd', '5EUI710')
